land/unpack/R3BLandCosmic1.cxx

Removed an include in R3BLandCosmic1.cxx which caused problems on a mac.

removed include to fix compile error on mac

---

.gitignore
macros/r3b/geo/create_neuland_demo_geo.C
macros/r3b/land/tdrV2/.gitignore
macros/r3b/land/tdrV2/calibr_mini.c
macros/r3b/land/tdrV2/preCalibr.c
macros/r3b/land/tdrV2/r3blandsim.c
macros/r3b/neuland/.gitignore
macros/r3b/neuland/demo/Step2_Digitizing.sh
macros/r3b/neuland/matrices/Step0_CreateAllGeometryFiles.sh
macros/r3b/neuland/matrices/Step1_Simulate.C
macros/r3b/neuland/matrices/Step1_Simulate.sh
macros/r3b/neuland/matrices/Step2_DigitizingClustering.C
macros/r3b/neuland/matrices/Step2_DigitizingClustering.sh
macros/r3b/neuland/matrices/Step3_Calibr.sh
macros/r3b/neuland/matrices/calibr.C
macros/r3b/neuland/matrices/calibr_mini.C
macros/r3b/neuland/matrices/drawStyle.C
macros/r3b/neuland/matrices/eventDisplay.C
macros/r3b/r3ball.C
neuland/R3BNeulandDigitizer.cxx

Save an image of the created geometry
Use LandPoint if NeulandPoints not available
Macros for different NeuLAND detector sizes
Updated macros
Gitignore files

NeuLAND Update 1603

---

r3bsource/R3BPspxReader.h

R3BPspxReader missed a forward declaration causing a make-error with root v6.08.02.

Added TClonesArray forward declaration

---

land/calibration/R3BNeulandHitFiller.cxx
land/calibration/R3BNeulandHitFiller.h
macros/r3b/land/test/Land_cosmic1_test.C

Exchanged TRandom1 with TRandom3.
Reduced amount of events -> way less time required.
Only 90% of PMTs have to be calibrated now.

NeulandCal2Hit Test fix

---

.travis.yml

New travis image provides less disk space resulting in an error.
Workaround uses old image until next image provides more disk space again.

Changed .travis.yml for workaround

---

macros/r3b/CMakeLists.txt
macros/r3b/run_aladin_digi.C
macros/r3b/run_aladin_digi_test.sh.in
macros/r3b/run_digi.C
macros/r3b/run_digi_test.sh.in
macros/r3b/run_test_new.sh.in

- Add run_sim.C and run_aladin_sim.C to the tests - together with digitizers.
- Add dTOF and Fibers(4,5,6,sfi) digitizers to the standard macro.

Some restructuring of standard macros for simulation.

---

macros/r3b/CMakeLists.txt
macros/r3b/test/testR3BPhaseSpaceGeneratorIntegration.C
r3bgen/CMakeLists.txt
r3bgen/R3BGenLinkDef.h
r3bgen/R3BPhaseSpaceGenerator.cxx
r3bgen/R3BPhaseSpaceGenerator.h
r3bgen/testR3BPhaseSpaceGenerator.cxx

For a lot of simulations it was necessary to generate input files for primary particle with TGenPhaseSpace first, one for each different set of parameters. With enough entries for high statistics, the file size was 50MB or more. This eliminates this intermediate file by directly integrating TGenPhaseSpace as a generator.

Add Phase Space Generator.

---

CMakeLists.txt
r3bdata/R3BDetectorList.h
r3bdata/R3BMCTrack.cxx

Include ID's of SOFIA detectors (currently 1 example) into R3BDetectorList.h and R3BMCTrack.cxx

Support for SOFIA simulations

---

.travis.yml
macros/r3b/test/testR3BPhaseSpaceGeneratorIntegration.C
r3bgen/CMakeLists.txt
r3bgen/testR3BPhaseSpaceGenerator.cxx

Travis CI has increased the size of the virtual machines. Using deprecated image is not necessary anymore.
Fixed FairPrimaryGenerator problem with a temporary workaround.

Removed temporary Travis config and fixed FairPrimaryGenerator Problem

---

psp/R3BPspxCal2Hit.cxx

Added "using namespace std;" to remove compile error in PspxCal2Hit

Removed compile error in PspxCal2Hit

---

califa/R3BCalifaCrystalCal2Hit.cxx
califa/R3BCalifaCrystalCal2Hit.h
califa/R3BCalifaGeometry.cxx

Select channel from double reading crystals based on a threshold
For double reading channels (S444 and beyond) the clusterfinder takes the
information from the gammaBranch if both are present and energy is below
a given fDRThreshold, user configurable. If energy is above the fDRThreshold,
it takes the protonBranch.

Modification for the CALIFA cluster finder in S444

---

tracker/unpackams/R3BAmsStripCal2Hit.cxx

Fixed a memory leak regarding an unbalanced new TSpectrum() in R3BAmsStripCal2Hit, with help from Philipp.

fixed memory leak, together with Philipp Klenze

---

field/R3BGladFieldMap.cxx

Two errors are corrected in this commit:
- correct initialization of the rotation angle of the field components. Before the
angle was not initializated and the field components were expressed in map field coordinates
instead of R3B coordinates.
- correct the symmetry properties of the magnetic field pseudovector: a Bx component had a
wrong sign.

Correct errors reading and rotating the components of the GLAD field

---

r3bgen/R3BAsciiGenerator.cxx
r3bgen/R3BAsciiGenerator.h

When more events are requested then are stored in an input file, the R3BAsciiGenerator will now simply start reading the file again. (The Monte-Carlo transport codes use a different, independent seed for each event, thus repetition of primary particles should not be an issue if the file is only repeated a few times.)
Also, some cleanup:
- No unnecessary pointers
- Using `FairLogger` instead of `std::cout`
- clang-format

Ascii Generator starts over if EoF is reached.

---

r3bgen/R3BCosmicGenerator.cxx

In c++ 11 sin() is declared as non-constexpr. Therefore make Sqr() and Sin2() functions non-constexpr.

Remove constexpr declaration.

---

neuland/shared/TCAConnector.h

Is needed because of compilation error on Debian 8 with gcc 4.9.2

Use TString::Data() when passing argument to runtime_error

---

califa/CMakeLists.txt
califa/CalifaLinkDef.h
califa/R3BCalifaCrystalCal2Hit.cxx
califa/R3BCalifaCrystalCal2Hit.h
califa/R3BCalifaGeometry.cxx
califa/R3BCalifaGeometry.h
califa/R3BCalifaOnlineSpectra.cxx
califa/R3BCalifaOnlineSpectra.h
califa/unpack/R3BCalifaDemoOnlineSpectra.cxx
califa/unpack/R3BCalifaDemoOnlineSpectra.h
califa/unpack/R3BCalifaMapped2CrystalCalPar.cxx
califa/unpack/R3BCalifaMapped2CrystalCalPar.h

Removed WR histograms from califa online
Removed all califa online histograms and old code
Califa: First histograms for commissioning
Added more histograms for califa online
Added califaMappingPar container to CalifaMapped2CrystalCalPar to manage automatically the crystal calibration
Added hit level histograms for califa online
CALIFA: Changed crystal ID for gamma range to 2432
Added more histograms to califa online and clang-format

Added CALIFA online for the experiments of 2020

---

.cmake-format
CMakeLists.txt
neuland/reconstruction/Neutron2DCalibr.cxx
neuland/reconstruction/Neutron2DCalibr.h
neuland/simulation/R3BNeulandMCMon.cxx
neuland/simulation/R3BNeulandMCMon.h
neuland/simulation/R3BNeulandPrimaryInteractionFinder.cxx
neuland/simulation/R3BNeulandPrimaryInteractionFinder.h
neuland/test/CMakeLists.txt
passive/CMakeLists.txt
passive/PassiveLinkDef.h
passive/R3BNeutronWindowAndSomeAir.cxx
passive/R3BNeutronWindowAndSomeAir.h
r3bdata/R3BMCStack.cxx
r3bdata/R3BMCTrack.cxx
r3bdata/R3BMCTrack.h
r3bgen/CMakeLists.txt
r3bgen/R3BAsciiGenerator.cxx
r3bgen/R3BAsciiGenerator.h
r3bgen/R3BPhaseSpaceGenerator.cxx
r3bgen/R3BPhaseSpaceGenerator.h
r3bgen/test/CMakeLists.txt
r3bgen/test/testR3BPhaseSpaceGeneratorIntegration.C

Change Ascii Generator to take masses from Geant4 NIST and compressed input files. Can still read input files with masses, will discard those.
R3BPhaseGen no longer takes a FairIon, but (Z,A) and retrieves the mass from Geant4 NIST.
Rework R3BMCTrack to use context sensitve ROOT/Math/Vector4Ds. Fixes MCTracks not storing mass.
Provide an Erel spectra in R3BNeulandMCMon.
Copy primary neutron tracks in R3BNeulandPrimaryInteractionFinder.
Refactor calorimetric method, fix leaks when using Neutron2DCalibr multiple times without closing the shell/process.
Fixes #338

Mass handling in Generators and R3BMCTrack:

---

atima/AtimaLinkDef.h
atima/R3BAtima.cxx
atima/R3BAtima.h

The stopping power at entrance and exit was missing a multiplication with the mass of the projectile.
I also added the target structs for more comfort over the CLI.

Fixed a missing conversion after a hint from Sonja Storck

---

r3bsource/R3BUcesbSource.cxx
r3bsource/R3BUcesbSource.h

Ucesb has gained the ability to get more detailed information about how the mapping went during the setup(). This introduces also a change in the interface, so quick action is needed.
Also fix up a comment that was outdated.

Support for the new version of ext_data_setup() in R3BUcesbSource.

---

music/R3BMusicCal2Hit.cxx
music/R3BMusicCal2Hit.h
r3bdata/musicData/R3BMusicHitData.cxx
r3bdata/musicData/R3BMusicHitData.h
r3bsource/R3BTrloiiTpatReader.cxx

Due to relatively high-rate events from CALIFA DAQ, there are many events stored with no TPAT value recorded. In the TPAT class, there is a container to store the number of TPAT values in a certain event. If no TPAT value stored, TPAT will be set to 0. This update has been done with Hans and Bastian.
Modification in the classes for R3BMusic. For the dedicated analysis getting rid of the beta dependency, it is necessary to provide averaged energy for outside of the class.
A similar modification has been applied in the TwinMUSIC classes, in the sofia repository.

Improvement of the TPAT reconstruction, and Updated R3BMusic classes

---

CMakeLists.txt

Especially the upcoming FairRoot 19 will no longer distribute find_package2 and require users to get it from FairCMakeModules.
So start slowly by using FairCMakeModules, if it's available.

Start to use FairCMakeModules

---

CMakeLists.txt

FairLogger in newer versions supports an external fmt.
Let's find_package2 all of them, so the appropriate targets are defined.

find_package2() for FairLogger deps

---

neuland/calibration/R3BNeulandCal2HitPar.cxx
r3bbase/R3BOnlineSpectraLosStandalone.h
r3bbase/R3BOnlineSpectraLosVsSci2.cxx
r3bbase/R3BOnlineSpectraSfib.h
sfib/R3BSfibCal2Hit.cxx

I was trying to compile with newer versions of ROOT and C++17 (namely: apr21 / Fairroot 18.6).
It looks like some more `#include`s are needed.
Those don't seem to hurt on jun19 / Fairroot 18.2.
So let's do this!

Add missing #include for newer ROOT / C++

---

evtvis/R3BCalifaEventDisplay.cxx
evtvis/R3BCalifaEventDisplay.h
evtvis/R3BCalifaHitEventDisplay.cxx
evtvis/R3BCalifaHitEventDisplay.h
evtvis/R3BMCTracks.cxx
evtvis/R3BMCTracks.h
r3bbase/CMakeLists.txt
r3bbase/R3BFileSource.cxx
r3bbase/R3BFileSource.h
r3bgen/R3BINCLRootGenerator.cxx

- `R3BINCLRootGenerator.cxx`: Added missing include
- `FairMCTracks` has beend removed from FairRoot. Here, remove unused references and roll code into `R3BMCTracks`
- `R3BFileSource.cxx`: Add a define to deal with ActivateObjectAnyImpl, added in FairRoot 18.4
- `R3BFileSource.h`: `SpecifyRunId` is not implemented, which leads to crashes. As it is required by the base class, provide a dummy implementation marked as fixme.
Note: Why does `R3BFileSource` even exist in the first place? It is only used in `R3BEventHeaderCal2Hit` for some Run Id shenanigans. Please solve this in a way that does not create duplication with `FairFileSource`, i.e. by deriving from `FairFileSource` instead of `FairSource`. The naming of `R3BEventHeaderCal2Hit` does not match its function. My guess is that some …

Compatibility with FairRoot 18.4+

---

neuland/calibration/CMakeLists.txt
neuland/calibration/NeulandCalibrationLinkDef.h
neuland/calibration/R3BNeulandCal2Hit.cxx
neuland/calibration/R3BNeulandCal2Hit.h
neuland/calibration/R3BNeulandHitModulePar.h
neuland/calibration/R3BNeulandHitPar.cxx
neuland/calibration/R3BNeulandMapped2CalPar.cxx
neuland/calibration/R3BNeulandProvideTStart.cxx
neuland/calibration/R3BNeulandProvideTStart.h
neuland/calibration/R3BNeulandTSyncer.cxx
neuland/online/R3BNeulandOnlineSpectra.cxx
neuland/online/R3BNeulandOnlineSpectra.h

R3BNeulandCal2Hit - fDistanceToTarget, fGlobalTimeOffset, fEnergyCutoff,
fWalkEnabled added and properly initialized
- GetTimeOffset(side) bug fixed in R3BNeulandHitModulePar.h
- the time offset set to 0 in remainder() function for time
- barID from 1 in NeulandHits
- z-coordinate of hit bug fixed
R3BNeulandProvideTStart added for the proton beamtime 2020
R3BNeulandTSyncer - tdiff shift introduced for large time shifts in data
R3BNeulandOnlineSpectra.cxx - some histograms added, bug fixed ...

Neuland stuff

---

r3bsource/R3BUcesbSource.cxx
r3bsource/R3BUcesbSource.h

R3BUcesbSource can now skip events without TPat

R3BUcesbSource can now skip events without TPat

---

r3bbase/R3BEventHeader.h

For convenience of the users less used to pushing bits around, I have added two helper methods to R3BEventHeader.
MakeTpatBit(n), where n is a trigNo, generates a bit mask. 
HasTpatTrig checks if a specific trigger is set in the tpat or not. 
Usage example (testing):
root [0] R3BEventHeader h
(R3BEventHeader &) Name:  Title: 
root [2] R3BEventHeader::MakeTpatBit(0)
Error in <TRint::HandleTermInput()>: std::runtime_error caught: Bad trigNo.
root [4] R3BEventHeader::MakeTpatBit(17)
Error in <TRint::HandleTermInput()>: std::runtime_error caught: Bad trigNo.
root [5] R3BEventHeader::MakeTpatBit(16)
(unsigned int) 32768
root [6] h.SetTpat(0xf)
root [8] h.HasTpatTrig(5)
(bool) false
root [9] h.HasTpatTrig(4)
(bool) true

added tpat related helper methods

---

music/calibration/R3BMusicCal2Hit.cxx
music/calibration/R3BMusicCal2Hit.h

The new variable Esum_nba_rot in #635 didn't reflect the energy average, but rather a sqrt of the energy average.
Also, AddHitData is merged into one with default arguments.

Fix bug of R3BMusicCal2Hit induced in a recent modification.

---

neuland/digitizing/DigitizingEngine.cxx
neuland/digitizing/DigitizingEngine.h
neuland/digitizing/DigitizingTacQuila.cxx
neuland/digitizing/DigitizingTacQuila.h
neuland/digitizing/DigitizingTamex.cxx
neuland/digitizing/DigitizingTamex.h
neuland/digitizing/R3BNeulandDigitizer.cxx

1. Apply clang-format on the new implemented NeuLAND digitisation code.
2. Fixing a potential infinite loop which could occur when digitisation class has no getter methods.

clang formatting and fixing potential infinite loop of NeuLAND digitization

---

.gitignore
neuland/calibration/CMakeLists.txt
neuland/calibration/LSQR.cxx
neuland/calibration/NeulandCalibrationLinkDef.h
neuland/calibration/R3BNeulandCal2Hit.cxx
neuland/calibration/R3BNeulandCal2HitPar.cxx
neuland/calibration/R3BNeulandMapped2Cal.cxx
neuland/calibration/R3BNeulandMapped2Cal.h
neuland/calibration/R3BNeulandMapped2CalPar.cxx
neuland/calibration/R3BNeulandMapped2CalPar.h
neuland/calibration/R3BNeulandMappingPar.cxx
neuland/calibration/R3BNeulandMappingPar.h
neuland/calibration/R3BNeulandParFact.cxx
neuland/calibration/R3BNeulandTSyncer.cxx
neuland/calibration/R3BNeulandTacquilaMapped2Cal.cxx
neuland/online/R3BNeulandOnlineSpectra.cxx
neuland/online/R3BNeulandOnlineSpectra.h
neuland/preexp/CMakeLists.txt
neuland/preexp/R3BNeulandGainMatching.cxx
r3bdata/neulandData/R3BNeulandCalData.cxx
r3bdata/neulandData/R3BNeulandCalData.h
r3bsource/neuland/R3BNeulandTamexReader.cxx
r3bsource/neuland/R3BNeulandTamexReader.h
r3bsource/neuland/ext_h101_raw_nnp_tamex.h

- in reader NeulandTrigMappedData + option fSkiptriggertime
- Mapped2CalPar
- Mapped2Cal - fTriggerTime in NeulandCalData
- Cal2HitPar, Cal2Hit - trigger time subtracted
NeulandOnlineSpectra updated
GainMatching modified in preexp
Clang-format
R3BNeulandMappingPar added

Trigger times added to Neuland

---

alpide/online/R3BAlpideOnlineSpectra.cxx
r3bbase/R3BEventHeader.cxx
r3bbase/R3BEventHeader.h
r3bdata/alpideData/R3BAlpideMappedData.cxx
r3bdata/alpideData/R3BAlpideMappedData.h
r3bsource/alpide/R3BAlpideReader.cxx
r3bsource/alpide/R3BAlpideReader.h
r3bsource/alpide/ext_h101_alpide.h
r3bsource/ams/R3BWhiterabbitAmsReader.cxx
r3bsource/base/R3BReader.h
r3bsource/base/R3BUnpackReader.cxx
r3bsource/base/R3BUnpackReader.h
r3bsource/califa/R3BWhiterabbitCalifaReader.cxx
r3bsource/foot/R3BWhiterabbitFootReader.cxx
r3bsource/los/R3BWhiterabbitLosReader.cxx
r3bsource/music/R3BWhiterabbitMusicReader.cxx
r3bsource/neuland/R3BWhiterabbitNeulandReader.cxx
r3bsource/wr/R3BWhiterabbitMasterReader.cxx
r3bsource/wr/R3BWhiterabbitPspReader.cxx
r3bsource/wr/R3BWhiterabbitReader.cxx
r3bsource/wr/R3BWhiterabbitS2Reader.cxx
r3bsource/wr/R3BWhiterabbitS8Reader.cxx

Changed fEventHeader.Eventno() to uint64_t
Clang-format for the alpide reader

Update for ALPIDE-demon

---

r3bsource/base/R3BUcesbSource.cxx

If the event header in FairRunOnline is not set to R3BEventHeader before its initialisation, FairRun would create an event header in type `FairEventHeader` and register it in `FairRootManager`. Such automatic creation of event header happens after the initialisation of source in `FairRunOnline::Init()`. Therefore, we can checking if R3BEventHeader is already set or not in `R3BUcesbSource::Init()`. If not, we set it to the R3BEventHeader(not owned). Note that registration of event header is not needed here since `FairRunOnline` will register it later.

Fixing a potential segmentation error from R3BUcesbSource

---

neuland/shared/Validated.h

The validation class in `R3BRoot/neuland/shared` folder is used to wrap the data with a validated tag. User can only get the value of the data if it's validated. This is very useful if the data value needs heavy calculations. And the recalculation of the data is only required if the data is invalidated, which could improves the efficiency of algorithms.
Following changes of the `Validated` class can further improves the efficiency, especially when data is very large and copying becomes very expensive.

Update of Neuland validated data class

---

CMakeLists.txt

Unless, of course, there are no "correct" versions of root macros. Like Adorno said, "Es gibt kein richtiges Leben im Falschen". 
Still, pointing them to the non-dev branch of the macros is even less correct.

Have people use the correct versions of the macros.

---

CMakeLists.txt
R3BRoot_test.cmake

I think we should enable libstdc++ asserts (such as for vector boundaries) per default.

enabled _GLIBCXX_ASSERTIONS

---

ssd/calibration/R3BFootMapped2StripCal.cxx
ssd/calibration/R3BFootMapped2StripCal.h

I introduce a new parameter fNStrip that is the number of strip hit for FOOT. This parameter was hardcoded before, now it is possible to set the value of this parameter in the unpacking macro.

Small update for Map2Cal FOOT
