macros/r3b/neuland/cpt/Step0_R3BNeulandSim.c, macros/r3b/neuland/cpt/Step0_R3BNeulandSim.sh, macros/r3b/neuland/cpt/Step1_Digitizing.c, macros/r3b/neuland/cpt/Step1_Digitizing.sh, macros/r3b/neuland/cpt/Step2_Monitoring.c, macros/r3b/neuland/cpt/Step2_Monitoring.sh, macros/r3b/neuland/monitoring/03-DigiMonitoringLand.sh, macros/r3b/neuland/monitoring/DigiMonitoringLand.c, macros/r3b/neuland/monitoring/R3BNeulandSim.c, macros/r3b/neuland/monitoring/compare.c, neuland/R3BNeulandDigiMon.cxx, neuland/R3BNeulandDigiMon.h, neuland/R3BNeulandDigitizer.cxx, neuland/R3BNeulandDigitizer.h, neuland/R3BNeulandMCMon.cxx, neuland/R3BNeulandMCMon.h, neuland/R3BNeulandVisualizer.cxx, neuland/R3BNeulandVisualizer.h, neuland/digitizing/DigitizingEngine.h
Monitors and macros:
- for investigation of NeuLAND hit properties before and after digitization
- for investigation of NeuLAND charged particle response
- optional 3D Visualization (for nice plots)
Digitizer Task and Engine:
- refactoring
- Fix HasFired() for paddle
- some documentation
=> Updates for NeuLAND Digitizer, Monitors and Macros:

macros/r3b/unpack/s438b/unpack_ucesb.C, r3bsource/R3BUcesbSource.cxx, r3bsource/R3BUcesbSource.h
Cope with stupidity of FairRunOnline::Run() argument interpretation.
Note: Fixes issue #12
=> Add Limit to ucesb events.

land/unpack/R3BLandAna.cxx, land/unpack/R3BLandAna.h, land/unpack/R3BLandCosmic1.cxx, land/unpack/R3BLandCosmic1.h, land/unpack/R3BLandCosmic1Util.h, land/unpack/R3BLandTSync.cxx, land/unpack/R3BLandTSync.h, land/unpack/R3BLandTSyncModulePar.cxx, land/unpack/R3BLandTSyncModulePar.h, macros/r3b/unpack/s438b/cosmic1.C
Removed unnecessary parts in cosmic1. Changed types to match root types. Fixed bugs, causing wrong tsync values. Fixed a bug causing compile error on mac with root 5.
=> Cosmic1 Update

land/unpack/R3BLandAna.cxx, land/unpack/R3BLandMapping.cxx, land/unpack/R3BLandMapping.h, land/unpack/R3BLandRawAna.cxx, land/unpack/R3BNeulandMapped2Cal.cxx, land/unpack/R3BNeulandMapped2Cal.h, land/unpack/R3BNeulandMapped2CalPar.cxx, los/unpack/R3BLosTcal.cxx, los/unpack/R3BLosTcal.h, los/unpack/R3BLosTcalFill.cxx, macros/r3b/unpack/s438b/cosmic1.C, macros/r3b/unpack/s438b/tsync_s438b_lmd_beam.C, macros/r3b/unpack/s438b/view_tcal_resolution.C, neuland/unpack/R3BNeulandTcal.cxx, neuland/unpack/R3BNeulandTcal.h, neuland/unpack/R3BNeulandTcalFill.cxx, r3bdata/neulandData/R3BNeulandMappedData.cxx, r3bdata/neulandData/R3BNeulandMappedData.h, r3bsource/R3BNeulandTacquilaReader.cxx, tcal/R3BTCalEngine.cxx, tcal/R3BTCalEngine.h, tcal/R3BTCalModulePar.cxx, tcal/R3BTCalModulePar.h, tcal/R3BTCalPar.cxx, tcal/R3BTCalPar.h
Change single index in TCAL calibration to plane/paddle/side indexing.
Added tsync macro for beam data. Standard time offset value for s438b. Minor changes.
Draw and Print functions, accessible from Context Menu in TBrowser.
=> New TCAL indexing: plane, paddle, side.

actar/GarfieldPhysics.cxx
Properly determine the Sensor area.
Add 2 X planes in electrical field for ACTAR.
=> Load geometry for Garfield++ from TGeoManager.

land/calibration/R3BNeulandMapped2Cal.cxx, land/calibration/R3BNeulandMapped2QCalPar.cxx, land/calibration/R3BNeulandMapped2QCalPar.h, land/calibration/R3BNeulandQCalPar.h
QCal-Pars are now accessed with plane,bar,side instead of id --> more clearly code.
Fixed a bug.
Removed old QCal File
Adjusted Comments
=> Land QCalPar fix

Dart.sh, macros/r3b/land/CMakeLists.txt, macros/r3b/land/test/CMakeLists.txt, macros/r3b/land/test/Land_cosmic1_test.C, macros/r3b/land/test/Land_qcal_test.C, macros/r3b/land/test/Land_tcal_test.C, macros/r3b/land/test/run_test.sh.in
Added QCal , TCal and Cosmic1 tests for NeuLAND
Changed Dart.sh: terminal wont close anymore
=> Added QCal , TCal and Cosmic1 tests for NeuLAND

land/CMakeLists.txt, land/LandLinkDef.h, land/calibration/R3BNeulandHitFiller.cxx, land/calibration/R3BNeulandHitFiller.h, land/calibration/R3BNeulandQCalFiller.cxx, land/calibration/R3BNeulandQCalFiller.h, macros/r3b/land/test/CMakeLists.txt, macros/r3b/land/test/Land_cosmic1_test.C, macros/r3b/land/test/Land_qcal_test.C, macros/r3b/land/test/run_test.sh.in
Added Test Classes, because Root 5 is unable to override virtual methods for classes defined in a macro.
Increased timeout of cosmic1-test form 30min to 60min.
=> Added Classes for Testing

r3bbase/R3BDetector.cxx, r3bbase/R3BDetector.h, r3bbase/R3BModule.cxx, r3bbase/R3BModule.h
Position and rotation of R3BDetector and R3BModule can now be set inside macros.
=> Position and rotation of R3B-Geometry can now be set inside macros

neuland/CMakeLists.txt, neuland/clustering/CMakeLists.txt, neuland/digitizing/CMakeLists.txt, neuland/reconstruction/CMakeLists.txt, r3bsource/CMakeLists.txt, r3bsource/R3BLinkDef.h, r3bsource/R3BWhiterabbitReader.cxx, r3bsource/R3BWhiterabbitReader.h, r3bsource/ext_h101_whiterabbit.h
Please pull soon! Oleg needs this.
=> Feature whiterabbit reader

macros/r3b/r3ball.C, neuland/R3BNeuland.cxx, neuland/R3BNeuland.h
Fixes for failing build under Root 5 (sorry).
landreco test might still fail, not sure what to do about that.
=> Fixes for Root5 and landreco test

.travis.yml, Dart.sh, R3BRoot_test.cmake
=> Added Travis CI Support

field/R3BAladinFieldMap.cxx, field/R3BAladinFieldMap.h, land/R3BLandDigitizer.cxx, land/R3BLandDigitizer.h, land/calibration/R3BLandCosmic1LSQR.cxx, land/calibration/R3BLandCosmic1LSQR.h, startrack/unpack/R3BStartrackMapped2Cal.cxx
Hi, since a while I'm operating a custom branch of R3BRoot, which can be linked against executables (and also has a lot of other stuff in it which is relevant to me).
This pull-request is essentially a reasoned git cherry-pick of that branch to apply the fixes and enable GNU ld to link executables against all R3B libraries, leaving out other mods (irrelevant to this issue) and quite a bit of history clutter.
=> linker-fixes

califa/CMakeLists.txt, califa/CalifaLinkDef.h, califa/R3BCalifaContFact.cxx, califa/R3BCalifaContFact.h, califa/unpack/R3BCalifaCrystalCalPar.cxx, califa/unpack/R3BCalifaCrystalCalPar.h, califa/unpack/R3BCalifaMapped2CrystalCal.cxx, califa/unpack/R3BCalifaMapped2CrystalCal.h, califa/unpack/R3BCalifaMapped2CrystalCalPar.cxx, califa/unpack/R3BCalifaMapped2CrystalCalPar.h, macros/r3b/unpack/califa/califa_febex3_ucesb2.C, macros/r3b/unpack/califa/checkResults.C, r3bgen/testR3BPhaseSpaceGenerator.cxx
Modifying Califa Calibration classes and macros
Solving mistakes and adding libraries(Spectrum) to CMake
Improving the containerParameter
Including the class R3BCalifaMapped2CrystalCal
Solving problems and adding a new function to get parameters
Small modifications
Adding the checkResults.C and the energy smearing
Adding channel smearing
Adding channel smearing
=> Califa Energy Calibration

psp/R3BPspxCal2Hit.cxx, psp/R3BPspxCal2Hit.h, psp/R3BPspxMapped2Precal.cxx, psp/R3BPspxMapped2Precal.h, psp/R3BPspxPrecal2Cal.cxx, psp/R3BPspxPrecal2Cal.h, psp/par/R3BPspxPrecalPar.cxx, r3bdata/pspData/R3BPspxHitData.cxx, r3bdata/pspData/R3BPspxHitData.h, r3bdata/pspData/R3BPspxMappedData.cxx, r3bdata/pspData/R3BPspxMappedData.h, r3bdata/pspData/R3BPspxPrecalData.h, r3bsource/R3BPspxReader.cxx, r3bsource/R3BPspxReader.h
Main change is a new PspxReader, which is necessary for unpacking the KVI data.
=> Feature pspx

r3bdata/CMakeLists.txt, r3bdata/R3BDataLinkDef.h, r3bdata/fibData/R3BFi4CalItem.cxx
=> Put back missing R3BFi4CalItem.cxx file.

r3bdata/R3BMCStack.cxx, r3bdata/R3BMCStack.h, r3bdata/R3BMCTrack.cxx, r3bdata/R3BMCTrack.h
=> Store number of points in an std::array.

fi7/R3BFi7Digitizer.cxx, fi8/R3BFi8Digitizer.cxx, neuland/shared/R3BNeulandOnlineSpectra.h, r3bbase/R3BGlobalAnalysis.cxx
- Add missing include <array> in R3BNeulandOnlineSpectra.
- Fix logger warnings.
=> Fix compilation error on macOS.

califa/unpack/R3BCalifaOnlineSpectra.cxx, califa/unpack/R3BCalifaOnlineSpectra.h, tracker/unpackams/R3BAmsMapped2StripCalPar.cxx, tracker/unpackams/R3BAmsMapped2StripCalPar.h
AMS: Print parameters for the DAQ
=> AMS: Print parameters for the DAQ

neuland/calibration/R3BNeulandCal2Hit.cxx, neuland/calibration/R3BNeulandCal2Hit.h, neuland/digitizing/R3BNeulandHitMon.cxx, neuland/digitizing/R3BNeulandHitMon.h, neuland/shared/CMakeLists.txt, neuland/shared/NeulandSharedLinkDef.h, neuland/shared/R3BNeulandOnlineReconstruction.cxx, neuland/shared/R3BNeulandOnlineReconstruction.h, neuland/shared/R3BNeulandOnlineSpectra.cxx, neuland/shared/R3BNeulandOnlineSpectra.h, neuland/shared/TCAConnector.h, r3bsource/R3BNeulandTamexReader.cxx, r3bsource/R3BNeulandTamexReader.h
- Introduce NeuLAND Online Reconstruction with 3D Display
- Cal2Hit: Hit time with beam if start available, fix orientation
- NeulandTamexReader: Deduce number of panels from nnp header
- NeulandHitMon: Flight Distance Adjusted ToF
- TCA Connector: New `OptionalInputConnector` that doesn't throw if the requested branch is missing
=> NeuLAND Beam Me Up

califa/R3BCalifaCrystalCal2Hit.cxx, califa/R3BCalifaCrystalCal2Hit.h, califa/R3BCalifaGeometry.cxx, califa/unpack/R3BCalifaOnlineSpectra.cxx, califa/unpack/R3BCalifaOnlineSpectra.h, r3bdata/trackerData/R3BTraPoint.cxx, r3bdata/trackerData/R3BTraPoint.h, tracker/R3BTra.cxx, tracker/R3BTra.h
CALIFA: Load califa geometry in the class CalifaCrystalCal2Hit from initialization
CALIFA Hit: Added debug info
AMS: Changed name of some parameters for simulation
=> AMS and CALIFA: some modifications

field/R3BGladFieldMap.cxx
By default the GLAD field map is now defined in all 4 quadrants of xy plane.
Adopt R3BGladMap.cxx.
=> Add full description of GLAD field map

r3bdata/musicData/R3BMusicMappedData.cxx, r3bdata/musicData/R3BMusicMappedData.h, r3bsource/CMakeLists.txt, r3bsource/R3BLinkDef.h, r3bsource/R3BMusicReader.cxx, r3bsource/R3BMusicReader.h, r3bsource/ext_h101_music.h
remove section information for the R3BMusic (only one section in the detector)
adding the musicData directory in the CMakeList
=> Add the reader for the R3BMusic

music/R3BMusicOnlineSpectra.cxx, music/R3BMusicOnlineSpectra.h
Removed tcanvas duplicated in the music online class
=> Added music histograms for energy vs difference of DT

califa/CMakeLists.txt, califa/CalifaLinkDef.h, califa/R3BCalifaContFact.cxx, califa/R3BCalifaMappingPar.cxx, califa/R3BCalifaMappingPar.h
Correct a typo in the name of a parameter
=> Add new califaMappingPar container for the CALIFA lookup table data

r3bdata/amsData/R3BAmsHitData.cxx, r3bdata/amsData/R3BAmsHitData.h, r3bdata/amsData/R3BAmsMappedData.h, r3bdata/amsData/R3BAmsStripCalData.h, tracker/CMakeLists.txt, tracker/R3BTraContFact.cxx, tracker/TraLinkDef.h, tracker/unpackams/R3BAmsMapped2StripCal.cxx, tracker/unpackams/R3BAmsMapped2StripCal.h, tracker/unpackams/R3BAmsMapped2StripCalPar.cxx, tracker/unpackams/R3BAmsMapped2StripCalPar.h, tracker/unpackams/R3BAmsMappingPar.cxx, tracker/unpackams/R3BAmsMappingPar.h, tracker/unpackams/R3BAmsStripCal2Hit.cxx, tracker/unpackams/R3BAmsStripCal2Hit.h
Added amsMappingPar container to R3BAmsMapped2StripCalPar for getting the calibration parameters
AMS:Changed again to 5 times the value of sigma to accept signals from strips
AMS:Included new geometry for data at Hit level
=> Added R3BAmsMappingPar container for lookup table of AMS detectors

califa/R3BCalifaMappingPar.cxx, califa/R3BCalifaOnlineSpectra.cxx, califa/R3BCalifaOnlineSpectra.h, califa/unpack/R3BCalifaCrystalCalPar.cxx, califa/unpack/R3BCalifaDemoOnlineSpectra.cxx, califa/unpack/R3BCalifaDemoOnlineSpectra.h, tracker/unpackams/R3BAmsMappingPar.cxx
CALIFA: Added function to draw histograms as a function of febex or preamp channels
CALIFA:Finish Preamp to Febex sequence for online histograms
=> CALIFA: Basic changes for containers and new functions for online

los/CMakeLists.txt, los/R3BLosProvideTStart.cxx, los/R3BLosProvideTStart.h, neuland/calibration/R3BNeulandCal2Hit.cxx, neuland/calibration/R3BNeulandCal2Hit.h, neuland/online/CMakeLists.txt, neuland/online/R3BNeulandOnlineReconstruction.cxx, neuland/online/R3BNeulandOnlineReconstruction.h, neuland/online/R3BNeulandOnlineSpectra.cxx, neuland/online/R3BNeulandOnlineSpectra.h, r3bbase/R3BEventHeader.cxx, r3bbase/R3BEventHeader.h
With respect to #332 :
- add TStart field to R3BEventHeader
- write Detector/Experiment specific Tasks that set that value, to be selected in macros
- Los Example included
- Sofia->Sofia Repo
- use value in NeuLAND Tasks
There is a TimeStamp field, but that is (rarely) used and I don't know its full meaning.
=> Provide TStart to R3BEventHeader

califa/ana/R3BCalifaOnlineSpectra.cxx, r3bdata/amsData/R3BAmsHitData.cxx, r3bdata/amsData/R3BAmsHitData.h, r3bdata/trackerData/R3BTraPoint.h, tracker/R3BTra.cxx, tracker/unpackams/R3BAmsMapped2StripCalPar.cxx, tracker/unpackams/R3BAmsOnlineSpectra.cxx, tracker/unpackams/R3BAmsOnlineSpectra.h, tracker/unpackams/R3BAmsStripCal2Hit.cxx, tracker/unpackams/R3BAmsStripCal2Hit.h
Added more materials to R3BTra class and alpide sensors as active volume
Simple modification in the R3BAmsMapped2StripCalPar class
clang-format
Initialized wrm in R3BCalifaOnlineSpectra class
=> Added angles theta and phi for simulations with alpide sensors

tof/R3BTofdCal2Histo.cxx, tof/R3BTofdCal2Histo.h, tof/R3BTofdCal2HistoPar.cxx, tof/R3BTofdCal2HitS454.cxx, tof/R3BTofdCal2HitS454.h, tof/R3BTofdMapped2Cal.cxx
fixed ToFd bugs: Some errors may occur if one wants to calculate calibration parameters; some histograms where set to the wrong range/binning
removed obsolete LOS stuff from ToFd: LOS is not longer needed in ToFd so I removed that part.
removed time shifting as we calculate ToFd times relative to the trigger-time now
=> Tofd update

califa/CMakeLists.txt, califa/CalifaLinkDef.h, califa/pars/R3BCalifaContFact.cxx, califa/pars/R3BCalifaCrystalPars4Sim.cxx, califa/pars/R3BCalifaCrystalPars4Sim.h, califa/sim/R3BCalifaDigitizer.cxx, califa/sim/R3BCalifaDigitizer.h
- Experimental parameters added to the simulation (thresholds and resolutions)
- New parameter container for simulation
- Fixed bug in the digitizer class
=> Added New Features For CALIFA Simulation

r3bgen/R3BCosmicGenerator.cxx, r3bgen/R3BDistribution1D.cxx
The bug caused to slightly overestimate the start of the distribution
=> Fixed a small bug and some readability improvments for R3BDistribution1D

califa/sim/R3BCalifaDigitizer.cxx
Fixed Bug in R3BCalifaDigitizer
=> Fixed Bug in R3BCalifaDigitizer

r3bgen/CMakeLists.txt, r3bgen/R3BBeamProperties.cxx, r3bgen/R3BBeamProperties.h, r3bgen/R3BCosmicGenerator.h, r3bgen/R3BDistribution1D.cxx, r3bgen/R3BDistribution2D.cxx, r3bgen/R3BDistribution2D.h, r3bgen/R3BDistribution3D.cxx, r3bgen/R3BGenLinkDef.h, r3bgen/R3BIonGenerator.cxx, r3bgen/R3BIonGenerator.h, r3bgen/R3BParticleGenerator.cxx, r3bgen/R3BParticleGenerator.h, r3bgen/R3BParticleSelector.cxx, r3bgen/R3BParticleSelector.h, r3bgen/R3BPhaseSpaceGenerator.cxx, r3bgen/R3BPhaseSpaceGenerator.h, r3bgen/README.md, r3bgen/test/testR3BPhaseSpaceGeneratorIntegration.C
I do not know, if this is useful for anybody else, but I felt like there is a very simple single particle generator missing.
First, I wanted to simplify/update R3BIonGenerator, but I am not sure who uses it where.
That is why I added this class.
It uses R3BDistribution and allows a quick simulation setup:
`auto gen = new R3BParticleGenerator();`
`gen->SetProton(); `
`gen->SetEnergyDistribution(R3BDistribution1D::Flat(0, 1000));`
`gen->SetVertexDistribution(R3BDistribution3D::Delta( 0, 0, 0));`
Please let me know if you have any suggestions!
=> Added a simple Generator for one single particle.

califa/CMakeLists.txt, califa/CalifaLinkDef.h, califa/ana/R3BCalifaCrystalCal2TotCalPar.cxx, califa/ana/R3BCalifaCrystalCal2TotCalPar.h, califa/ana/R3BCalifaMapped2CrystalCalPar.cxx, califa/ana/R3BCalifaOnlineSpectra.cxx, califa/pars/R3BCalifaContFact.cxx, califa/pars/R3BCalifaTotCalPar.cxx, califa/pars/R3BCalifaTotCalPar.h, califa/unpack/R3BCalifaMapped2CrystalCal.cxx, califa/unpack/R3BCalifaMapped2CrystalCal.h
Califa: Added Tot calibration
Added elastic generator for califa calibration
clang format
rm r3bgen/R3BElasticppGenerator classes
=> Califa: Added Tot calibration

califa/R3BCalifaCrystalCal2Hit.cxx, califa/R3BCalifaCrystalCal2Hit.h, califa/R3BCalifaGeometry.cxx, califa/R3BCalifaGeometry.h, tracker/unpackams/R3BAmsOnlineSpectra.cxx, tracking/R3BTGeoPar.cxx, tracking/R3BTGeoPar.h
Solved AMS online warnings in R3BAmsOnlineSpectra.cxx
=> Update of R3BTGeoPar class and solved AMS online warnings

califa/online/R3BCalifaOnlineSpectra.cxx, califa/online/R3BCalifaOnlineSpectra.h, tracker/unpackams/R3BAmsOnlineSpectra.cxx, tracker/unpackams/R3BAmsOnlineSpectra.h
Added Nf vs Ns histogram for Califa
=> Online modifications for AMS and Califa

music/CMakeLists.txt, music/R3BMusicContFact.cxx, tracker/unpackams/R3BAmsOnlineSpectra.cxx, tracker/unpackams/R3BAmsOnlineSpectra.h
AMS:Histogram selection as a function of the number of detectors
=> AMS: Added amsMappingPar container to online

califa/calibration/R3BCalifaMapped2CrystalCalPar.cxx, los/R3BLosCal2HitPar.h, los/R3BLosMapped2Cal.cxx, los/R3BLosMapped2Cal.h, r3bbase/CMakeLists.txt, r3bbase/R3BLinkDef.h, r3bbase/R3BOnlineSpectraLosStandalone.cxx, r3bbase/R3BOnlineSpectraLosStandalone.h, r3bsource/R3BLinkDef.h, r3bsource/R3BLosReader.cxx, r3bsource/R3BLosReader.h
Solved problem with califa calibration
Update code for s515
=> Added R3BOnlineSpectraLosStandalone class developed by Aleksandra et al

r3bbase/R3BOnlineSpectraFiberTofds515.cxx, r3bbase/R3BOnlineSpectraFiberTofds515.h, r3bbase/R3BOnlineSpectraLosVsSci2.cxx, r3bbase/R3BOnlineSpectraLosVsSci2.h, r3bbase/R3BOnlineSpectraSci2.cxx
clean ext_h101_sci2.h
add the Tref channel (to channel #3)
clang-format -i R3BSci2Reader.cxx
add online spectra for Sci2 at mapped level
cosmetics
add Sci2TcalData
add Mapped2Tcal for Sci2
Add ToF spectrum from S2 to Cave C
Added also AoverQ
FRS-ID: Update for s515
=> FRS-ID: Update for s515

psp/R3BPspxOnlineSpectra.cxx, psp/R3BPspxOnlineSpectra.h
Updated online analysis of PSPs for s515
=> Feature pspx sonja

CMakeLists.txt, README.md, r3bbase/CMakeLists.txt, r3bbase/R3BEventHeaderCal2Hit.cxx, r3bbase/R3BFileSource.cxx, r3bbase/R3BFileSource.h, r3bbase/R3BLinkDef.h, r3bbase/R3BWhiterabbitPropagator.cxx, r3bbase/R3BWhiterabbitPropagator.h, r3bsource/R3BWhiterabbitCalifaReader.cxx, r3bsource/R3BWhiterabbitReaderImpl.h
nothing
Added whiterabbit propagator for data analysis
Update of R3BFileSource class
Cosmetic changes
Cosmetic changes
Cosmetic change
Update readme
=> Added runid to the R3BEventHeaderCal2Hit class for its propagation

.gitignore, cmake/modules/FindAtima.cmake, cmake/modules/FindEPICS.cmake, cmake/modules/FindGarfield.cmake, cmake/modules/Finducesb.cmake, cmake/modules/WriteEnvCache.cmake, r3bsource/README.md
Ucesb: added colors to indicate the paths clearly
Cosmetic changes for cmake files
Added GPL licence to cmake files
Update r3bsource readme a bit
=> Ignore changes in the detector root geometries

r3bdata/CMakeLists.txt, r3bdata/R3BDataLinkDef.h, r3bdata/trloiiData/R3BTrloiiData.cxx, r3bdata/trloiiData/R3BTrloiiData.h, r3bsource/CMakeLists.txt, r3bsource/R3BTrloiiScalerReader.cxx, r3bsource/R3BTrloiiScalerReader.h, r3bsource/SourceLinkDef.h, r3bsource/ext/ext_h101_trlo.h
=> TRLOII: Added data structure to unpack the scaler info

califa/calibration/R3BCalifaMapped2CrystalCal.cxx
As I wrote in a mail this week, the new upexps unpackers will map the barrel crystals to their crystal id, never to id+2432, which was used for barrel channels in proton range before. 
To allow people to keep using their old calibration files with the new unpackers, I added the following mechanism:
If your cal[id] is zero or nan (you wish),
And cal[id+2432] is nonzero,
Then make cal[id]=cal[id+2432] in case you are using the new unpacker (where barrel is always in [1, 1952]) with an old calibration (where proton barrel channels were in [2433, 4384]). 
Also, fixed another double free in a destructor (exceptions (e.g. strdup) aside, DO NOT FREE WHAT YOU DID NOT ALLOC) and delete/delete[] confusion (as I was already running valgrinds memcheck).
Because I could not figure out how to get this …
=> califa map2cal: legacy barrel proton range calibration fix

los/R3BLosProvideTStart.cxx, neuland/calibration/R3BNeulandCal2Hit.cxx, neuland/calibration/R3BNeulandCal2HitPar.cxx, neuland/calibration/R3BNeulandMapped2Cal.cxx, neuland/calibration/R3BNeulandMapped2CalPar.cxx, neuland/calibration/R3BNeulandMappedHist.cxx, neuland/calibration/R3BNeulandProvideTStart.cxx, neuland/calibration/R3BNeulandTacquilaMapped2Cal.cxx, neuland/calibration/R3BNeulandTacquilaMapped2CalPar.cxx, neuland/online/R3BNeulandOnlineReconstruction.cxx, neuland/online/R3BNeulandOnlineSpectra.cxx, neuland/preexp/R3BNeulandCheckMapping.cxx, neuland/preexp/R3BNeulandGainMatching.cxx, neuland/preexp/R3BNeulandTimeRes.cxx, neuland/unpack/R3BNeulandTcalFill.cxx, r3bsource/ext/ext_h101_raw_nnp_tamex.h
ext_h101 file for 25 planes
GainMatching vtarget.A -> vtarget
=> Compatibility with new event header name R3BEventHeader -> EventHeader.

analysis/AnaLinkDef.h, r3bdata/CMakeLists.txt, r3bdata/R3BDataLinkDef.h, r3bdata/alpideData/R3BAlpideCalData.cxx, r3bdata/alpideData/R3BAlpideCalData.h, r3bdata/alpideData/R3BAlpidePoint.h
Solved problem with R3BRpcvsLosOnlineSpectra, forgotten in the file AnaLinkDef.h
=> Added caldata for alpide sensors

rpc/CMakeLists.txt, rpc/calibration/R3BRpcCal2Hit.cxx, rpc/calibration/R3BRpcCal2Hit.h, rpc/calibration/R3BRpcCal2HitPar.cxx, rpc/calibration/R3BRpcCal2HitPar.h, rpc/calibration/R3BRpcMapped2PreCal.cxx, rpc/calibration/R3BRpcMapped2PreCal.h, rpc/calibration/R3BRpcMapped2PreCalPar.cxx, rpc/calibration/R3BRpcMapped2PreCalPar.h, rpc/calibration/R3BRpcPreCal2Cal.cxx, rpc/calibration/R3BRpcPreCal2Cal.h, rpc/calibration/R3BRpcPreCal2CalPar.cxx, rpc/calibration/R3BRpcPreCal2CalPar.h, rpc/online/R3BRpcOnlineSpectra.cxx, rpc/online/R3BRpcOnlineSpectra.h, tcal/R3BTCalContFact.cxx
- Update of data classes from @ManuelXarepe
- Update of RPC Online
=> Update of RPC data classes and online 

musli/online/R3BMusliOnlineSpectra.cxx, musli/online/R3BMusliOnlineSpectra.h
=> Add Delta DT to R3BMusliOnline

rpc/calibration/R3BRpcCal2Hit.cxx, rpc/calibration/R3BRpcCal2Hit.h, rpc/calibration/R3BRpcCal2HitPar.cxx, rpc/calibration/R3BRpcCal2HitPar.h, rpc/online/R3BRpcOnlineSpectra.cxx, rpc/online/R3BRpcOnlineSpectra.h, rpc/pars/R3BRpcHitPar.cxx, rpc/pars/R3BRpcHitPar.h
- Online changes
- Cal2Hit changes from @ManuelXarepe
=> Last rpc changes

rpc/CMakeLists.txt, rpc/online/R3BRpcOnlineSpectra.cxx, rpc/online/R3BRpcOnlineSpectra.h
- Included LOS in rpc CMakeLists
- LOS correlations in the online
- Mean charge histograms
=> LOS Correlations in the RPC Online

analysis/AnaLinkDef.h, analysis/online/R3BCalifavsFootOnlineSpectra.cxx, analysis/online/R3BCalifavsFootOnlineSpectra.h, califa/online/R3BCalifaOnlineSpectra.cxx
=> Added R3BCalifavsFootOnlineSpectra

alpide/CMakeLists.txt, alpide/calibration/R3BAlpideCal2Hit.cxx, alpide/calibration/R3BAlpideCal2Hit.h, alpide/calibration/R3BAlpideMapped2Cal.cxx, alpide/online/R3BAlpideOnlineSpectra.cxx, alpide/online/R3BAlpideOnlineSpectra.h, alpide/pars/R3BAlpideCluster.cxx, alpide/pars/R3BAlpideCluster.h, alpide/pars/R3BAlpideMappingPar.cxx, alpide/pars/R3BAlpideMappingPar.h, alpide/pars/R3BAlpideNoisyPixels.cxx, alpide/pars/R3BAlpideNoisyPixels.h, r3bdata/alpideData/R3BAlpideCalData.cxx, r3bdata/alpideData/R3BAlpideCalData.h, r3bdata/alpideData/R3BAlpideHitData.cxx, r3bsource/alpide/R3BAlpideReader.cxx, r3bsource/alpide/R3BAlpideReader.h, r3bsource/alpide/ext_h101_alpide.h
- Update R3BAlpideMappingPar container and added R3BAlpideCal2Hit class
- Update R3BAlpideOnlineSpectra and R3BAlpideCal2Hit classes
=> New implementation for ALPIDE silicon detectors

r3bdata/CMakeLists.txt, r3bdata/DataLinkDef.h, r3bdata/musliData/R3BMusliCalData.cxx, r3bdata/musliData/R3BMusliCalData.h, r3bdata/musliData/R3BMusliHitData.cxx, r3bdata/musliData/R3BMusliHitData.h
clang format
Add R3BMusliHitData class to r3bdata/musliData
Debug the setters of R3BMusliCalData.h
=> Add R3BMusliCalData class in r3bdata/muslidata

musli/CMakeLists.txt, musli/calibration/R3BMusliMapped2Cal.cxx, musli/calibration/R3BMusliMapped2Cal.h, musli/pars/R3BMusliCalPar.cxx, musli/pars/R3BMusliCalPar.h, musli/pars/R3BMusliContFact.cxx, musli/pars/R3BMusliContFact.h, twim/pars/R3BTwimCalPar.cxx, twim/pars/R3BTwimCalPar.h
R3BMusliContFact class
fix a typo in method SetPosParams of R3BTwimCalPar
fix typo in getParams in R3BTwimCalPar class
R3BMusliMapped2Cal class
=> Music LIGHT IONS : Mapped 2 Cal step

analysis/online/R3BFibervsTofDOnlineSpectra.cxx, fiber/online/R3BFiberMAPMTCorrelationOnlineSpectra.cxx, fiber/online/R3BFiberMAPMTOnlineSpectra.cxx, music/sim/R3BMusic.cxx, music/sim/R3BMusic.h, mwpc/mwpc0/R3BMwpc0.cxx, tofd/online/R3BTofDOnlineSpectra.cxx, tofd/online/R3BTofDOnlineSpectra.h, tofd/sim/R3BTofD.cxx, tofd/sim/R3BTofD.h
- Minor modifications for TofD
- Added TFolder for fiber onlines
=> Update simulation classes for Music, Mwpc0 and TofD

analysis/CMakeLists.txt, analysis/offline/R3BAnalysisIncomingID.cxx, analysis/offline/R3BAnalysisIncomingID.h, fiber/bunched/R3BBunchedFiberCal2Hit.cxx, fiber/bunched/R3BBunchedFiberMapped2Cal.cxx, fiber/bunched/R3BBunchedFiberMapped2CalPar.cxx, fiber/bunched/R3BBunchedFiberMapped2CalPar.h, fiber/bunched/R3BBunchedFiberSPMTTrigMapped2Cal.cxx, fiber/bunched/R3BBunchedFiberSPMTTrigMapped2Cal.h, fiber/bunched/R3BBunchedFiberSPMTTrigMapped2CalPar.cxx, fiber/bunched/R3BBunchedFiberSPMTTrigMapped2CalPar.h, r3bbase/R3BTcutPar.cxx, r3bbase/R3BTimeStitch.cxx, r3bsource/fibers/R3BBunchedFiberSPMTTrigReader.cxx
Update R3BTimeStitch
Update BunchedFiber classes
=> Added Musli hit data to R3BAnalysisIncomingID for PID from FRS

analysis/online/R3BOnlineSpillAnalysis.cxx, fiber/CMakeLists.txt, fiber/mapmt/R3BFiberMAPMTCal2Hit.cxx, fiber/pars/R3BFiberContFact.cxx, fiber/sim/R3BFiber.cxx, los/online/R3BLosOnlineSpectra.cxx, los/online/R3BLosOnlineSpectra.h
Added some corrections proposed by Enis for R3BFiberMAPMTCal2Hit, R3BOnlineSpillAnalysis and R3BLosOnlineSpectra
New canvas for LOS online
=> Update R3BFiber and R3BFiberContFact for the new simulation protocols

musli/CMakeLists.txt, musli/MusliLinkDef.h, musli/calibration/R3BMusliCal2Hit.cxx, musli/calibration/R3BMusliCal2Hit.h, musli/calibration/R3BMusliMapped2Cal.cxx, musli/calibration/R3BMusliMapped2Cal.h, musli/pars/R3BMusliContFact.cxx, musli/pars/R3BMusliHitPar.cxx, musli/pars/R3BMusliHitPar.h, r3bdata/musliData/R3BMusliCalData.cxx, r3bdata/musliData/R3BMusliCalData.h, r3bdata/musliData/R3BMusliHitData.cxx, r3bdata/musliData/R3BMusliHitData.h
change MusliCalData and MusliHitData formats
MusliHitPar class implemented
Add Cal2Hit step with Z and theta calculation
debug
=> MusliCal2Hit : load the HitPar and TGeoPar in ContFact

musli/CMakeLists.txt, musli/MusliLinkDef.h, musli/calibration/R3BMusliCal2Hit.cxx, musli/calibration/R3BMusliMapped2Cal.cxx, musli/calibration/R3BMusliMapped2CalPar.cxx, musli/calibration/R3BMusliMapped2CalPar.h, musli/pars/R3BMusliCalPar.cxx
empty R3BMusliMapped2CalPar.cxx created
debug the empty class R3BMusliMapped2CalPar
Read the input TClonesArray
R3BMusliMapped2CalPar : calculation of PosParams
debug
=> creation of the R3BMusliMapped2CalPar class

califa/online/R3BCalifaOnlineSpectra.cxx
..so the randomization of crystal angles shows correctly.
=> Minor changes in the binning of online angular histograms

musli/calibration/R3BMusliCal2Hit.cxx, musli/calibration/R3BMusliCal2Hit.h, musli/online/R3BMusliOnlineSpectra.cxx, musli/online/R3BMusliOnlineSpectra.h, r3bdata/musliData/R3BMusliCalData.h, r3bdata/musliData/R3BMusliHitData.cxx, r3bdata/musliData/R3BMusliHitData.h
Add E and DT 1D spectra at CAL level
Adapt R3BMusliCal2Hit to the new fX argument
R3BMusliOnlineSpectra : add 1D histo for E, Z and Theta
add 2D histo at HIT level
new beta correction to be coherent with the observed dependency
=> R3BMusliOnlineSpectra : add Cal and Hit data

musli/calibration/R3BMusliCal2Hit.cxx, musli/calibration/R3BMusliCal2Hit.h, musli/calibration/R3BMusliMapped2Cal.cxx, musli/calibration/R3BMusliMapped2Cal.h, musli/online/R3BMusliOnlineSpectra.cxx, musli/online/R3BMusliOnlineSpectra.h, musli/online/R3BMusliVsMwpcOnlineSpectra.cxx, r3bdata/musliData/R3BMusliCalData.cxx, r3bdata/musliData/R3BMusliCalData.h
fix memory leak
remove useless argument of CalData
adapt code to the new CalData format
add mult spectra at the CAL level
debug
cosmetics
adjust binning
=> allows to reach Hit Level with direct beam (no FRS)

analysis/offline/R3BAnalysisIncomingID.cxx, analysis/offline/R3BIncomingBeta.cxx, analysis/offline/R3BIncomingBeta.h, analysis/online/R3BGeneralOnlineSpectra.cxx, analysis/online/R3BGeneralOnlineSpectra.h, analysis/online/R3BIncomingIDOnlineSpectra.cxx, analysis/online/R3BIncomingIDOnlineSpectra.h, musli/online/R3BMusliOnlineSpectra.cxx, r3bdata/frsData/R3BFrsData.cxx, r3bdata/frsData/R3BFrsData.h, r3bdata/rpcData/R3BRpcCalData.cxx, r3bdata/rpcData/R3BRpcCalData.h, r3bdata/rpcData/R3BRpcHitData.cxx, r3bdata/rpcData/R3BRpcHitData.h, r3bdata/rpcData/R3BRpcMappedData.cxx, r3bdata/rpcData/R3BRpcMappedData.h, r3bdata/rpcData/R3BRpcPreCalData.h
Update incoming analysis classes
Update R3BMusliOnlineSpectra
Clang-format for rpc data classes
=> Update R3BIncomingIDOnlineSpectra and analysis tasks

rpc/online/R3BRpcOnlineSpectra.cxx, rpc/online/R3BRpcOnlineSpectra.h
- Added OnSpill and OffSpill options
- Efficiency plots 
- ToF correlations
- Clean Up
=> Update of Rpc Online Spectra

analysis/offline/R3BAnalysisIncomingID.cxx, analysis/online/R3BIncomingIDOnlineSpectra.cxx, musli/online/R3BMusliOnlineSpectra.cxx, musli/online/R3BMusliOnlineSpectra.h, sci2/online/R3BOnlineSpectraSci2.cxx, sci2/online/R3BOnlineSpectraSci2.h
=> Update Musli, sci2 and incoming onlines

analysis/offline/R3BAnalysisIncomingID.cxx, analysis/online/R3BCalifavsTofDOnlineSpectra.cxx, analysis/online/R3BCalifavsTofDOnlineSpectra.h, fiber/bunched/R3BBunchedFiberMapped2Cal.cxx, fiber/mapmt/R3BFiberMAPMTMapped2Cal.cxx, fiber/pars/R3BFiberContFact.cxx, fiber/pars/R3BFiberContFact.h, tofd/pars/R3BTofDMapped2CalPar.cxx
=> Solved some problems with the R3BBunchedFiberMapped2Cal class

analysis/online/R3BCalifavsTofDOnlineSpectra.cxx, ssd/calibration/R3BAmsMapped2StripCal.cxx, ssd/calibration/R3BAmsMapped2StripCalPar.cxx, ssd/calibration/R3BAmsStripCal2Hit.cxx, ssd/calibration/R3BFootMapped2StripCal.cxx, ssd/calibration/R3BFootStripCal2Hit.cxx, ssd/calibration/R3BFootStripCal2Hit.h, ssd/online/R3BFootOnlineSpectra.cxx, ssd/pars/R3BFootCalPar.cxx, ssd/pars/R3BFootMappingPar.cxx, ssd/pars/R3BFootMappingPar.h
The problem was in the file R3BFootStripCal2Hit.h, in particular:
TH1F* hssd[10];    ----->  TH1F* hssd[20];
Initially it was defined for 10 detectors, but now you have more detectors. 
You can try to use:
std::vector<TH1F*> hssd;
and define the dimension later in the Init() function.
=> Solving problem with FOOT detectors for the Cal2Hit class

analysis/offline/R3BIncomingBeta.cxx, analysis/online/R3BIncomingIDOnlineSpectra.cxx, analysis/online/R3BIncomingIDOnlineSpectra.h, sci2/calib/R3BSci2Tcal2Hit.cxx
Added LOS-Z spectra with and without S2 requirement to inspect the S2 threshould.
=> Fix bug in R3BSci2Tcal2Hit.cxx

twim/calibration/R3BTwimMapped2Cal.cxx, twim/calibration/R3BTwimMapped2Cal.h, twim/pars/R3BTwimCalPar.cxx, twim/pars/R3BTwimCalPar.h
=> Drift time window introduced

fiber/digi/R3BFiberDigitizer.cxx
previous one was not working properly
=> Update Fiber digitizer

.gitignore, neuland/digitizing/DigitizingEngine.cxx, neuland/digitizing/DigitizingEngine.h, neuland/digitizing/DigitizingTamex.cxx, neuland/digitizing/DigitizingTamex.h, neuland/digitizing/R3BNeulandDigitizer.cxx, neuland/digitizing/R3BNeulandHitMon.cxx
Implementation of NeuLAND Tamex digitization module and the multi-hits feature of digitisation engine.
Now in digitisation module, each paddle/bar in NeuLAND can output multiple NeulandHits for each event.
=> Adding Tamex digitisation module to NeuLAND simulation

sci2/calib/R3BSci2Tcal2Hit.cxx, sci2/calib/R3BSci2Tcal2Hit.h
=> Update hit s2

analysis/offline/R3BAnalysisIncomingID.cxx, analysis/offline/R3BAnalysisIncomingID.h, analysis/offline/R3BIncomingBeta.cxx
R3BIncomingBeta: Added a fHeader->GetExpId() for 515
=> R3BAnalysisIncomingID: Added a LOS selector for the incomingID

alpide/calibration/R3BAlpideCal2Hit.cxx, alpide/geo/R3BAlpideGeometry.cxx, alpide/geo/R3BAlpideGeometry.h, alpide/online/R3BSingleAlpideCorrelationOnlineSpectra.cxx, alpide/sim/R3BAlpide.cxx, alpide/sim/R3BAlpide.h
ALPIDE: Added all the root geometries
Minor change for the ALPIDE geometry version by default
=> ALPIDE online: Color for some hists

r3bsource/base/R3BUcesbSource.cxx
Please do not merge yet.
Lets first see that it triggers the CI failure.  Then I'll push a better commit.
=> A spell fix.

cmake/scripts/config.csh.in, cmake/scripts/config.sh.in
Do not replace env by default.
=> defaulting to append in config.sh

analysis/offline/R3BTrackS454.cxx, analysis/online/R3BCalifavsFootOnlineSpectra.cxx, analysis/online/R3BCalifavsTofDOnlineSpectra.cxx, califa/CMakeLists.txt, califa/CalifaLinkDef.h, califa/README.md, califa/calibration/R3BCalifaCrystalCal2Cluster.cxx, califa/calibration/R3BCalifaCrystalCal2Cluster.h, califa/online/R3BCalifaDemoOnlineSpectra.cxx, califa/online/R3BCalifaOnlineSpectra.cxx, califa/pars/R3BCalifaClusterPar.cxx, califa/pars/R3BCalifaClusterPar.h, evtvis/CMakeLists.txt, evtvis/R3BCalifaClusterEventDisplay.cxx, evtvis/R3BCalifaClusterEventDisplay.h, evtvis/R3BEventDisplayLinkDef.h, r3bdata/CMakeLists.txt, r3bdata/DataLinkDef.h, r3bdata/califaData/R3BCalifaClusterData.cxx, r3bdata/califaData/R3BCalifaClusterData.h, ssd/online/R3BAmsCalifaCorrelatedOnlineSpectra.cxx, startrack/R3BStartrackEvent.cxx, startrack/R3BStartrackEvent.h
=> Renamed CalifaHit to CalifaCluster

los/calib/R3BLosTCal2Hit.cxx
Added a line to compile R3BRoot.
=> Include FairRootManager in R3BLosTCal2Hit.cxx

passive/R3BGladMagnet.cxx
=> Added offset of 2cm on the Y axis of GLAD

analysis/offline/R3BIncomingBeta.cxx, analysis/offline/R3BIncomingBeta.h, fiber/bunched/R3BBunchedFiberCal2Hit.cxx, fiber/bunched/R3BBunchedFiberCal2Hit.h, fiber/mapmt/R3BFiberMAPMTCal2Hit.cxx, fiber/mapmt/R3BFiberMAPMTCal2Hit.h, los/R3BLosProvideTStart.cxx, los/R3BLosProvideTStart.h, los/calib/R3BLosTCal2Hit.cxx, los/calib/R3BLosTCal2Hit.h, los/online/R3BLosOnlineSpectra.cxx, los/online/R3BLosOnlineSpectra.h, music/calibration/R3BMusicMapped2Cal.h, music/pars/R3BMusicMapped2CalPar.cxx, music/pars/R3BMusicMapped2CalPar.h, r3bbase/BaseLinkDef.h, r3bbase/R3BCoarseTimeStitch.cxx, r3bbase/R3BCoarseTimeStitch.h, rpc/calibration/R3BRpcCal2Hit.cxx, rpc/calibration/R3BRpcCal2Hit.h, tofd/calibration/R3BTofDCal2Hit.cxx, tofd/calibration/R3BTofDCal2Hit.h, tofd/online/R3BTofDOnlineSpectra.cxx, tofd/online/R3BTofDOnlineSpectra.h, tofd/pars/R3BTofDCal2HitPar.cxx, tofd/pars/R3BTofDCal2HitPar.h, twim/calibration/R3BTwimMapped2Cal.cxx, twim/calibration/R3BTwimMapped2Cal.h
In the case of using a CTDC with a clock of 150MHz, the initialization of R3BCoarseTimeStitch must be done as follows
fTimeStitch = new R3BCoarseTimeStitch();
fTimeStitch->SetClockTDC150();
=> Added more clock frequencies for CTDC electronics
